"""Embedded clinical metadata used by the inference engine."""

diseases = [{'base_severity': 'Urgent',
  'category': 'Parasitic Infection',
  'description': 'Mosquito-borne Plasmodium infection causing periodic high fever, chills, and sweating.',
  'icd10': 'B54',
  'id': 'malaria',
  'key_risk_factors': ['mosquito_exposure', 'endemic_travel'],
  'major_symptoms': ['chills', 'sweating', 'headache'],
  'mandatory_symptoms': ['fever'],
  'name': 'Malaria',
  'severity_triggers': ['jaundice',
                        'altered_mental_status',
                        'dark_urine',
                        'seizures',
                        'difficulty_breathing',
                        'abnormal_bleeding'],
  'supporting_symptoms': ['nausea_vomiting',
                          'fatigue',
                          'joint_pain',
                          'muscle_pain',
                          'diarrhea',
                          'dizziness',
                          'jaundice',
                          'dark_urine',
                          'weakness',
                          'confusion',
                          'cough',
                          'back_pain',
                          'pallor']},
 {'base_severity': 'Urgent',
  'category': 'Bacterial Infection',
  'description': 'Systemic Salmonella Typhi infection causing sustained fever, abdominal pain, and weakness.',
  'icd10': 'A01.0',
  'id': 'typhoid',
  'key_risk_factors': ['contaminated_water', 'street_food_exposure'],
  'major_symptoms': ['abdominal_pain', 'headache', 'weakness'],
  'mandatory_symptoms': ['fever'],
  'name': 'Typhoid Fever',
  'severity_triggers': ['gastrointestinal_bleeding', 'delirium'],
  'supporting_symptoms': ['diarrhea',
                          'loss_of_appetite',
                          'dry_cough',
                          'constipation',
                          'skin_rash',
                          'chills',
                          'nausea_vomiting']},
 {'base_severity': 'Urgent',
  'category': 'Respiratory Disease',
  'description': 'Inflammatory lung tissue infection causing productive cough, fever, and difficulty breathing.',
  'icd10': 'J18.9',
  'id': 'pneumonia',
  'key_risk_factors': ['smoking', 'chronic_lung_disease', 'recent_uri'],
  'major_symptoms': ['shortness_of_breath', 'fever', 'chest_pain'],
  'mandatory_symptoms': ['cough'],
  'name': 'Pneumonia',
  'severity_triggers': ['severe_dyspnea', 'cyanosis', 'hypoxia'],
  'supporting_symptoms': ['chills',
                          'fatigue',
                          'purulent_sputum',
                          'nausea_vomiting',
                          'diarrhea',
                          'altered_mental_status']},
 {'base_severity': 'Urgent',
  'category': 'Mycobacterial Infection',
  'description': 'Chronic M. tuberculosis infection causing persistent cough >3 weeks, hemoptysis, and night sweats.',
  'icd10': 'A15.0',
  'id': 'tuberculosis',
  'key_risk_factors': ['close_contact_tb', 'immunocompromised'],
  'major_symptoms': ['hemoptysis', 'night_sweats', 'unexplained_weight_loss'],
  'mandatory_symptoms': ['cough'],
  'name': 'Pulmonary Tuberculosis (TB)',
  'severity_triggers': ['massive_hemoptysis', 'severe_respiratory_distress'],
  'supporting_symptoms': ['fever',
                          'fatigue',
                          'chest_pain',
                          'loss_of_appetite',
                          'chills',
                          'shortness_of_breath',
                          'purulent_sputum']},
 {'base_severity': 'Normal',
  'category': 'Viral Respiratory Infection',
  'description': 'Contagious coronavirus infection presenting with fever, cough, anosmia, and dyspnea.',
  'icd10': 'U07.1',
  'id': 'covid19',
  'key_risk_factors': ['recent_exposure', 'unvaccinated'],
  'major_symptoms': ['fever', 'cough', 'loss_of_taste_smell'],
  'mandatory_symptoms': [],
  'name': 'COVID-19 (SARS-CoV-2)',
  'severity_triggers': ['oxygen_saturation_below_94', 'persistent_chest_pressure'],
  'supporting_symptoms': ['shortness_of_breath',
                          'fatigue',
                          'headache',
                          'sore_throat',
                          'chills',
                          'nasal_congestion',
                          'joint_pain',
                          'nausea_vomiting',
                          'diarrhea']},
 {'base_severity': 'Normal',
  'category': 'Viral Respiratory Infection',
  'description': 'Acute viral respiratory infection with sudden high fever, myalgia, and dry cough.',
  'icd10': 'J11.1',
  'id': 'influenza',
  'key_risk_factors': ['seasonal_epidemic'],
  'major_symptoms': ['cough', 'headache', 'chills'],
  'mandatory_symptoms': ['fever'],
  'name': 'Seasonal Influenza (Flu)',
  'severity_triggers': ['difficulty_breathing'],
  'supporting_symptoms': ['joint_pain',
                          'fatigue',
                          'nasal_congestion',
                          'sore_throat',
                          'nausea_vomiting',
                          'diarrhea',
                          'weakness']},
 {'base_severity': 'Urgent',
  'category': 'Arboviral Infection',
  'description': 'Arboviral infection with high fever, retro-orbital pain, and severe muscle/joint aches.',
  'icd10': 'A90',
  'id': 'dengue',
  'key_risk_factors': ['mosquito_exposure', 'tropical_travel'],
  'major_symptoms': ['retro_orbital_pain', 'joint_pain', 'skin_rash'],
  'mandatory_symptoms': ['fever'],
  'name': 'Dengue Fever',
  'severity_triggers': ['severe_abdominal_pain',
                        'spontaneous_bleeding',
                        'persistent_vomiting',
                        'rapid_breathing',
                        'blood_in_vomit_stool',
                        'cold_clammy_skin'],
  'supporting_symptoms': ['headache',
                          'nausea_vomiting',
                          'fatigue',
                          'weakness',
                          'swollen_glands',
                          'muscle_pain',
                          'bone_pain',
                          'loss_of_appetite',
                          'petechiae',
                          'easy_bruising',
                          'nose_bleeding',
                          'gum_bleeding',
                          'blood_in_urine',
                          'facial_flushing']},
 {'base_severity': 'Emergency',
  'category': 'Bacterial Enteric Infection',
  'description': 'Vibrio cholerae infection causing profuse rice-water diarrhea and rapid dehydration.',
  'icd10': 'A00.9',
  'id': 'cholera',
  'key_risk_factors': ['contaminated_water'],
  'major_symptoms': ['nausea_vomiting', 'dehydration'],
  'mandatory_symptoms': ['diarrhea'],
  'name': 'Cholera',
  'severity_triggers': ['hypovolemic_shock', 'anuria'],
  'supporting_symptoms': ['muscle_cramps', 'fatigue', 'dry_mouth_mucosa', 'oliguria_anuria', 'thirst', 'dizziness']},
 {'base_severity': 'Emergency',
  'category': 'Central Nervous System Infection',
  'description': 'Life-threatening CNS inflammation with high fever, nuchal rigidity, and altered mental state.',
  'icd10': 'G03.9',
  'id': 'meningitis',
  'key_risk_factors': ['recent_ear_sinus_infection'],
  'major_symptoms': ['fever', 'nuchal_rigidity', 'altered_mental_status'],
  'mandatory_symptoms': ['headache'],
  'name': 'Acute Meningitis',
  'severity_triggers': ['seizures', 'coma'],
  'supporting_symptoms': ['photophobia', 'nausea_vomiting', 'skin_rash', 'seizures', 'cold_hands_feet', 'diarrhea']},
 {'base_severity': 'Normal',
  'category': 'Chronic Airway Disease',
  'description': 'Chronic airway inflammation causing episodic wheezing, shortness of breath, and chest tightness.',
  'icd10': 'J45.901',
  'id': 'asthma',
  'key_risk_factors': ['allergens_exposure', 'family_history_atopy'],
  'major_symptoms': ['wheezing', 'cough', 'chest_pain'],
  'mandatory_symptoms': ['shortness_of_breath'],
  'name': 'Bronchial Asthma Exacerbation',
  'severity_triggers': ['inability_to_speak_full_sentences', 'silent_chest'],
  'supporting_symptoms': ['anxiety', 'fatigue', 'nasal_congestion', 'sore_throat']},
 {'base_severity': 'Normal',
  'category': 'Endocrine & Metabolic Disorder',
  'description': 'Metabolic disorder characterized by high blood glucose, polyuria, and polydipsia.',
  'icd10': 'E11.9',
  'id': 'diabetes_mellitus',
  'key_risk_factors': ['family_history_diabetes', 'obesity'],
  'major_symptoms': ['polyuria_polydipsia', 'unexplained_weight_loss'],
  'mandatory_symptoms': [],
  'name': 'Type 2 Diabetes Mellitus / Hyperglycemia',
  'severity_triggers': ['altered_consciousness_dka'],
  'supporting_symptoms': ['fatigue', 'blurred_vision', 'slow_wound_healing', 'recurrent_thrush', 'genital_itching']},
 {'base_severity': 'Normal',
  'category': 'Cardiovascular Disease',
  'description': 'Elevated arterial blood pressure presenting with occipital headache, dizziness, and epistaxis.',
  'icd10': 'I10',
  'id': 'hypertension',
  'key_risk_factors': ['high_sodium_diet', 'family_history'],
  'major_symptoms': ['headache', 'dizziness'],
  'mandatory_symptoms': [],
  'name': 'Essential Hypertension',
  'severity_triggers': ['systolic_bp_above_180', 'chest_pain'],
  'supporting_symptoms': ['chest_pain', 'blurred_vision']},
 {'base_severity': 'Normal',
  'category': 'Hematologic Disorder',
  'description': 'Reduction in red blood cell mass causing fatigue, pallor, and exertional dizziness.',
  'icd10': 'D50.9',
  'id': 'anemia',
  'key_risk_factors': ['heavy_menstrual_bleeding', 'poor_iron_intake'],
  'major_symptoms': ['pallor', 'dizziness'],
  'mandatory_symptoms': ['fatigue'],
  'name': 'Iron Deficiency Anemia',
  'severity_triggers': ['syncope', 'chest_pain'],
  'supporting_symptoms': ['shortness_of_breath', 'palpitations', 'headache', 'cold_hands_feet']},
 {'base_severity': 'Urgent',
  'category': 'Renal Disorder',
  'description': 'Renal impairment causing oliguria, peripheral edema, nausea, and electrolyte imbalance.',
  'icd10': 'N18.9',
  'id': 'kidney_disease',
  'key_risk_factors': ['longstanding_diabetes', 'hypertension'],
  'major_symptoms': ['fatigue', 'nausea_vomiting', 'flank_pain'],
  'mandatory_symptoms': [],
  'name': 'Chronic / Acute Kidney Failure',
  'severity_triggers': ['pulmonary_edema', 'uremic_encephalopathy'],
  'supporting_symptoms': ['peripheral_edema',
                          'oliguria_anuria',
                          'dark_urine',
                          'shortness_of_breath',
                          'itching',
                          'confusion']},
 {'base_severity': 'Urgent',
  'category': 'Hepatic Disorder',
  'description': 'Liver inflammation causing jaundice, right upper quadrant pain, and fatigue.',
  'icd10': 'K72.90',
  'id': 'liver_disease',
  'key_risk_factors': ['viral_hepatitis_exposure', 'alcohol_abuse'],
  'major_symptoms': ['abdominal_pain', 'fatigue'],
  'mandatory_symptoms': ['jaundice'],
  'name': 'Acute Hepatitis / Hepatic Dysfunction',
  'severity_triggers': ['hepatic_encephalopathy', 'coagulopathy_bleeding'],
  'supporting_symptoms': ['nausea_vomiting', 'dark_urine', 'loss_of_appetite', 'itching', 'pale_stools', 'joint_pain']},
 {'base_severity': 'Normal',
  'category': 'Gastrointestinal Disease',
  'description': 'Gastric or duodenal mucosal ulceration causing burning epigastric pain.',
  'icd10': 'K27.9',
  'id': 'peptic_ulcer',
  'key_risk_factors': ['h_pylori_infection', 'chronic_nsaid_use'],
  'major_symptoms': ['nausea_vomiting'],
  'mandatory_symptoms': ['abdominal_pain'],
  'name': 'Peptic Ulcer Disease',
  'severity_triggers': ['melena', 'hematemesis'],
  'supporting_symptoms': ['bloating', 'loss_of_appetite']},
 {'base_severity': 'Emergency',
  'category': 'Surgical Abdominal Emergency',
  'description': 'Inflammation of appendix causing RLQ pain migration, rebound tenderness, and fever.',
  'icd10': 'K35.80',
  'id': 'appendicitis',
  'key_risk_factors': ['age_10_to_30'],
  'major_symptoms': ['nausea_vomiting', 'fever'],
  'mandatory_symptoms': ['abdominal_pain'],
  'name': 'Acute Appendicitis',
  'severity_triggers': ['peritonitis', 'diffuse_pain'],
  'supporting_symptoms': ['loss_of_appetite',
                          'abdominal_swelling',
                          'constipation',
                          'diarrhea',
                          'inability_to_pass_gas']},
 {'base_severity': 'Normal',
  'category': 'Urological Infection',
  'description': 'Lower urinary tract infection causing dysuria, frequency, and suprapubic pain.',
  'icd10': 'N39.0',
  'id': 'urinary_tract_infection',
  'key_risk_factors': ['female_sex', 'sexual_activity'],
  'major_symptoms': ['urinary_frequency', 'abdominal_pain'],
  'mandatory_symptoms': ['dysuria'],
  'name': 'Acute Cystitis / UTI',
  'severity_triggers': ['flank_pain', 'high_fever_pyelonephritis'],
  'supporting_symptoms': ['fever', 'cloudy_urine', 'blood_in_urine', 'flank_pain', 'nausea_vomiting']},
 {'base_severity': 'Normal',
  'category': 'Immunological Reaction',
  'description': 'Hypersensitivity reaction causing hives, angioedema, pruritus, and respiratory distress.',
  'icd10': 'T78.40',
  'id': 'allergies',
  'key_risk_factors': ['known_food_drug_allergy'],
  'major_symptoms': ['skin_rash', 'urticaria_hives'],
  'mandatory_symptoms': [],
  'name': 'Acute Allergy / Anaphylaxis Risk',
  'severity_triggers': ['stridor_airway_swelling', 'hypotension'],
  'supporting_symptoms': ['shortness_of_breath', 'nasal_congestion', 'itching', 'facial_swelling', 'wheezing']},
 {'base_severity': 'Normal',
  'category': 'Neurological Disorder',
  'description': 'Neurovascular headache disorder with unilateral pulsating pain, photophobia, and nausea.',
  'icd10': 'G43.909',
  'id': 'migraine',
  'key_risk_factors': ['family_history', 'stress'],
  'major_symptoms': ['nausea_vomiting', 'photophobia'],
  'mandatory_symptoms': ['headache'],
  'name': 'Migraine Headache',
  'severity_triggers': ['thunderclap_onset'],
  'supporting_symptoms': ['dizziness', 'sensitivity_to_sound', 'visual_aura']},
 {'base_severity': 'Normal',
  'category': 'Musculoskeletal Disorder',
  'description': 'Joint inflammation causing pain, swelling, and morning stiffness.',
  'icd10': 'M19.90',
  'id': 'arthritis',
  'key_risk_factors': ['aging', 'joint_trauma'],
  'major_symptoms': ['joint_stiffness', 'joint_swelling'],
  'mandatory_symptoms': ['joint_pain'],
  'name': 'Osteoarthritis / Rheumatoid Arthritis',
  'severity_triggers': ['hot_red_single_septic_joint'],
  'supporting_symptoms': ['fatigue', 'joint_redness', 'reduced_joint_movement']},
 {'base_severity': 'Normal',
  'category': 'Gastrointestinal Infection',
  'description': 'Foodborne enteric infection causing sudden vomiting, diarrhea, and abdominal cramps.',
  'icd10': 'A05.9',
  'id': 'food_poisoning',
  'key_risk_factors': ['ingestion_spoiled_food'],
  'major_symptoms': ['nausea_vomiting', 'diarrhea', 'abdominal_pain'],
  'mandatory_symptoms': [],
  'name': 'Acute Gastroenteritis / Food Poisoning',
  'severity_triggers': ['bloody_stool', 'inability_to_keep_fluids_down_24h'],
  'supporting_symptoms': ['fever', 'headache', 'loss_of_appetite', 'muscle_cramps', 'dehydration']},
 {'base_severity': 'Urgent',
  'category': 'Fluid & Electrolyte Imbalance',
  'description': 'Deficit in body water causing thirst, dry mouth, dizziness, and dark urine.',
  'icd10': 'E86.0',
  'id': 'dehydration',
  'key_risk_factors': ['profuse_vomiting_diarrhea', 'heat_exposure'],
  'major_symptoms': ['fatigue', 'dizziness', 'dry_mouth_mucosa'],
  'mandatory_symptoms': [],
  'name': 'Acute Dehydration Syndrome',
  'severity_triggers': ['confusion_lethargy', 'hypotension'],
  'supporting_symptoms': ['nausea_vomiting', 'diarrhea', 'thirst', 'dark_urine', 'oliguria_anuria', 'weakness']}]


recommendations = {'allergies': {'first_aid': 'If mild: administer oral second-generation antihistamine (Cetirizine/Loratadine). IF '
                            'STRIDOR OR SWALLOWING DIFFICULTY: ADMINISTER INTRAMUSCULAR EPINEPHRINE IMMEDIATELY & CALL '
                            'EMERGENCY.',
               'lifestyle_guidance': 'Carry emergency epinephrine auto-injector, wear medical alert bracelet for '
                                     'severe allergies.',
               'specialist_referral': 'Allergist / Immunologist',
               'treatment_options': ['Intramuscular Epinephrine (EpiPen) 0.3mg for anaphylaxis',
                                     'Oral Antihistamines and topical corticosteroids for mild localized allergic '
                                     'reactions',
                                     'Allergen immunotherapy']},
 'anemia': {'first_aid': 'Rest, avoid sudden standing to prevent orthostatic syncope, ensure adequate fluid intake.',
            'lifestyle_guidance': 'Take iron supplements on an empty stomach with orange juice; avoid tea or coffee '
                                  'within 2 hours of iron intake.',
            'specialist_referral': 'Hematologist / Internal Medicine Specialist',
            'treatment_options': ['Oral Ferrous Sulfate/Gluconate supplementation with Vitamin C',
                                  'Dietary fortification with red meat, dark leafy greens, legumes',
                                  'Investigate and address underlying source of chronic blood loss']},
 'appendicitis': {'first_aid': 'NIL BY MOUTH (Do not eat or drink anything). DO NOT give laxatives or enemas. '
                               'IMMEDIATE SURGICAL EVALUATION.',
                  'lifestyle_guidance': 'Immediate hospitalization required.',
                  'specialist_referral': 'General Surgeon / Emergency Medicine Specialist',
                  'treatment_options': ['Urgent Appendectomy (Laparoscopic or Open)',
                                        'Pre-operative broad-spectrum IV antibiotics (Ceftriaxone + Metronidazole)',
                                        'IV fluid hydration and pain management']},
 'arthritis': {'first_aid': 'Apply warm heat packs for chronic stiffness or ice packs for acute joint swelling. Rest '
                            'joint.',
               'lifestyle_guidance': 'Low-impact weight-bearing exercise (swimming, cycling), maintain healthy body '
                                     'weight.',
               'specialist_referral': 'Rheumatologist / Orthopedic Specialist',
               'treatment_options': ['Acetaminophen or topical NSAIDs (Diclofenac gel) for osteoarthritis pain',
                                     'Disease-Modifying Antirheumatic Drugs (DMARDs e.g., Methotrexate) for Rheumatoid '
                                     'Arthritis',
                                     'Physical therapy and joint protection exercises']},
 'asthma': {'first_aid': 'Sit patient upright, administer 2-4 puffs of short-acting beta-agonist '
                         '(Salbutamol/Albuterol) via spacer immediately.',
            'lifestyle_guidance': 'Identify and avoid asthma triggers (dust mites, pollen, tobacco smoke, pet dander).',
            'specialist_referral': 'Pulmonologist / Allergist',
            'treatment_options': ['Inhaled Short-Acting Beta-Agonist (SABA) for acute rescue',
                                  'Inhaled Corticosteroid (ICS) + Formoterol maintenance controller',
                                  'Short course of oral Prednisolone for severe acute exacerbations']},
 'bronchitis': {'first_aid': 'Warm humidified air, adequate hydration, honey/throat lozenges for cough, rest.',
                'lifestyle_guidance': 'Avoid active and passive smoking, use room humidifier.',
                'specialist_referral': 'General Practitioner',
                'treatment_options': ['Supportive therapy: hydration and humidified air',
                                      'Inhaled bronchodilators if wheezing present',
                                      'Avoid unnecessary antibiotics (90%+ are viral)']},
 'cholera': {'first_aid': 'IMMEDIATE aggressive oral rehydration therapy (ORS). If unconscious or severe dehydration, '
                          "rapid IV Ringer's Lactate infusion.",
             'lifestyle_guidance': 'Boil all drinking water, wash hands thoroughly, ensure safe sewage disposal.',
             'specialist_referral': 'Emergency Medicine / Infectious Disease Specialist',
             'treatment_options': ["Rapid IV volume resuscitation with Ringer's Lactate or Normal Saline",
                                   'Oral Rehydration Solution (ORS) as tolerated',
                                   'Single-dose Doxycycline or Azithromycin to shorten illness duration']},
 'covid19': {'first_aid': 'Home isolation in dedicated room, pulse oximetry monitoring every 4 hours, oral hydration, '
                          'Paracetamol for fever/myalgia.',
             'lifestyle_guidance': 'Self-isolate for 5-7 days, wear N95 mask around others, practice frequent hand '
                                   'sanitation.',
             'specialist_referral': 'Infectious Disease / Pulmonology Specialist',
             'treatment_options': ['Symptomatic management for mild cases',
                                   'Paxlovid (Nirmatrelvir/Ritonavir) or Molnupiravir for high-risk early onset',
                                   'Dexamethasone and supplemental oxygen for severe hypoxemic cases']},
 'dehydration': {'first_aid': 'Administer Oral Rehydration Solution (ORS) slowly in small frequent sips. Rest in cool '
                              'shaded area.',
                 'lifestyle_guidance': 'Increase fluid intake during hot weather or physical exertion, monitor urine '
                                       'color (pale straw color indicates good hydration).',
                 'specialist_referral': 'Emergency Medicine Physician',
                 'treatment_options': ['Oral Rehydration Solution (ORS) for mild-to-moderate dehydration',
                                       "IV Normal Saline or Ringer's Lactate infusion for severe dehydration"]},
 'dengue': {'first_aid': 'Immediate fluid replacement with ORS or isotonic fluids. Paracetamol ONLY for fever '
                         '(STRICTLY AVOID Aspirin, NSAIDs, Ibuprofen due to bleeding risk).',
            'lifestyle_guidance': 'Use mosquito nets during daytime, wear long clothing, remove standing water '
                                  'containers.',
            'specialist_referral': 'Internal Medicine / Hematology Specialist',
            'treatment_options': ["Isotonic IV crystalloid fluid therapy (Normal Saline or Ringer's Lactate)",
                                  'Serial hematocrit and platelet count monitoring',
                                  'Blood product transfusion if plasma leakage or severe hemorrhage occurs']},
 'diabetes_mellitus': {'first_aid': 'Check capillary blood glucose immediately. If conscious and hypoglucemic (< 70 '
                                    'mg/dL), administer 15g fast-acting sugar.',
                       'lifestyle_guidance': 'Low glycemic index diet, 150 minutes of moderate aerobic exercise '
                                             'weekly, daily foot inspection.',
                       'specialist_referral': 'Endocrinologist / Diabetologist',
                       'treatment_options': ['Metformin as first-line oral hypoglycemic agent',
                                             'Second-line agents: SGLT2 inhibitors, GLP-1 receptor agonists, or '
                                             'Insulin',
                                             'HbA1c target monitoring every 3 months']},
 'food_poisoning': {'first_aid': 'Oral rehydration solution (ORS) sipping small amounts frequently, rest stomach for '
                                 '1-2 hours after vomiting.',
                    'lifestyle_guidance': 'Ensure food is cooked to safe internal temperatures, refrigerate perishable '
                                          'items promptly.',
                    'specialist_referral': 'Gastroenterologist / Family Physician',
                    'treatment_options': ['Oral fluid and electrolyte replacement',
                                          'Bland diet (BRAT diet: Bananas, Rice, Applesauce, Toast)',
                                          'Avoid anti-diarrheal agents (Loperamide) if bloody diarrhea or high fever '
                                          'present']},
 'hiv_screening': {'first_aid': 'Confidential medical evaluation and baseline serological/molecular testing.',
                   'lifestyle_guidance': 'Adherence to ART regimen, safe sex practices, psychological counseling '
                                         'support.',
                   'specialist_referral': 'Infectious Disease Specialist / HIV Clinic Counselor',
                   'treatment_options': ['Early initiation of Antiretroviral Therapy (ART) e.g., '
                                         'Tenofovir/Emtricitabine + Dolutegravir',
                                         'CD4 count and Viral Load baseline testing']},
 'hypertension': {'first_aid': 'Rest quietly in seated position for 15 minutes, recheck blood pressure. Seek emergency '
                               'care if BP > 180/120 with chest pain or headache.',
                  'lifestyle_guidance': 'DASH diet (salt intake < 2g/day), weight management, stress reduction, limit '
                                        'alcohol intake.',
                  'specialist_referral': 'Cardiologist / Nephrologist / Family Physician',
                  'treatment_options': ['Antihypertensive pharmacotherapy (ACE inhibitors/ARBs, Calcium Channel '
                                        'Blockers, Thiazide diuretics)',
                                        'Regular home blood pressure logging']},
 'influenza': {'first_aid': 'Bed rest, adequate warm fluids, Paracetamol/Ibuprofen for myalgia and fever. Avoid '
                            'Aspirin in children under 18.',
               'lifestyle_guidance': 'Annual seasonal flu vaccination, stay home until fever-free for 24 hours.',
               'specialist_referral': 'General Practitioner / Family Physician',
               'treatment_options': ['Neuraminidase inhibitors (Oseltamivir / Tamiflu) if initiated within 48 hours of '
                                     'symptom onset',
                                     'Symptomatic decongestants and cough suppressants']},
 'kidney_disease': {'first_aid': 'Strict fluid restriction, avoid all NSAID painkillers (Ibuprofen/Naproxen), monitor '
                                 'urine output.',
                    'lifestyle_guidance': 'Low sodium, low potassium, controlled protein diet under nephrology '
                                          'dietitian guidance.',
                    'specialist_referral': 'Nephrologist',
                    'treatment_options': ['ACE inhibitor / ARB therapy for renal protection (in CKD with proteinuria)',
                                          'Management of hyperkalemia, hyperphosphatemia, and anemia of CKD',
                                          'Dialysis or renal replacement therapy evaluation for end-stage renal '
                                          'disease']},
 'liver_disease': {'first_aid': 'Complete abstinence from alcohol, stop all non-essential medications, high-calorie '
                                'carbohydrate diet.',
                   'lifestyle_guidance': 'Strictly avoid alcohol, acetaminophen/paracetamol overdose, and herbal '
                                         'supplements.',
                   'specialist_referral': 'Hepatologist / Gastroenterologist',
                   'treatment_options': ['Antiviral treatment for chronic Hepatitis B or C',
                                         'Lactulose and Rifaximin for hepatic encephalopathy risk',
                                         'Diuretic therapy (Spironolactone/Furosemide) for ascites']},
 'malaria': {'first_aid': 'Ensure complete bed rest, maintain fluid intake with oral rehydration salts (ORS), and '
                          'administer antipyretic (Paracetamol) for fever above 38.5°C.',
             'lifestyle_guidance': 'Use insecticide-treated bed nets, eliminate standing water near dwelling, use '
                                   'mosquito repellent containing DEET.',
             'specialist_referral': 'Infectious Disease Specialist / Internal Medicine Physician',
             'treatment_options': ['Artemisinin-based Combination Therapy (ACT) e.g., Artemether-Lumefantrine for '
                                   'uncomplicated P. falciparum',
                                   'IV Artesunate or Quinine for severe malaria',
                                   'Daily fluid balance monitoring']},
 'meningitis': {'first_aid': 'IMMEDIATE EMERGENCY HOSPITAL TRANSPORT. Keep patient in quiet, dark room, protect '
                             'airway, do not flex neck.',
                'lifestyle_guidance': 'Prophylactic Rifampin or Ciprofloxacin for close household contacts.',
                'specialist_referral': 'Neurologist / Emergency Medicine / Critical Care Specialist',
                'treatment_options': ['Empiric IV Ceftriaxone + Vancomycin (+ Ampicillin if age > 50)',
                                      'IV Dexamethasone prior to or alongside first antibiotic dose',
                                      'Intensive care monitoring for elevated intracranial pressure']},
 'migraine': {'first_aid': 'Rest in a dark, quiet room with cold compress on forehead, stay hydrated.',
              'lifestyle_guidance': 'Maintain consistent sleep schedule, identify headache diary triggers (tyramine, '
                                    'aged cheese, missed meals).',
              'specialist_referral': 'Neurologist',
              'treatment_options': ['Acute abortive therapy: NSAIDs (Ibuprofen/Naproxen) or Triptans (Sumatriptan) at '
                                    'onset',
                                    'Prophylactic therapy (Propranolol, Topiramate, or CGRP inhibitors) for frequent '
                                    'attacks']},
 'peptic_ulcer': {'first_aid': 'Avoid spicy foods, caffeine, alcohol, and NSAID painkillers. Take antacid or H2 '
                               'blocker for acute epigastric pain.',
                  'lifestyle_guidance': 'Eat small frequent meals, discontinue smoking, avoid taking pain relievers on '
                                        'empty stomach.',
                  'specialist_referral': 'Gastroenterologist',
                  'treatment_options': ['Proton Pump Inhibitors (Omeprazole / Pantoprazole) for 4-8 weeks',
                                        'H. pylori eradication therapy (Triple therapy: PPI + Amoxicillin + '
                                        'Clarithromycin)',
                                        'Upper GI Endoscopy if alarm symptoms present (melena, weight loss)']},
 'pneumonia': {'first_aid': 'Position patient upright to facilitate breathing, administer humidified oxygen if '
                            'saturation is < 92%, keep warm.',
               'lifestyle_guidance': 'Absolute cessation of tobacco smoke, pneumococcal and annual influenza '
                                     'vaccination.',
               'specialist_referral': 'Pulmonologist / Critical Care Specialist',
               'treatment_options': ['Empiric antibiotic therapy (Amoxicillin/Clavulanate + Macrolide or Respiratory '
                                     'Fluoroquinolone)',
                                     'Chest physiotherapy and postural drainage',
                                     'Bronchodilators if bronchospasm present']},
 'sexually_transmitted_infection': {'first_aid': 'Abstain from all sexual contact until full medical evaluation and '
                                                 'treatment completion.',
                                    'lifestyle_guidance': 'Consistent use of barrier contraception (condoms), routine '
                                                          'STI screening.',
                                    'specialist_referral': 'Dermatovenereologist / Sexual Health Specialist',
                                    'treatment_options': ['Ceftriaxone IM single dose + Azithromycin PO for '
                                                          'Gonorrhea/Chlamydia empiric coverage',
                                                          'Partner notification and concurrent treatment']},
 'sinusitis': {'first_aid': 'Warm facial compresses, warm steam inhalation, saline nasal irrigation twice daily.',
               'lifestyle_guidance': 'Maintain good hydration, avoid sudden temperature changes.',
               'specialist_referral': 'Otolaryngologist (ENT Specialist)',
               'treatment_options': ['Intranasal corticosteroid spray (Fluticasone/Mometasone)',
                                     'Saline nasal lavage',
                                     'Amoxicillin-clavulanate if symptoms persist > 10 days or worsen (bacterial '
                                     'superinfection)']},
 'skin_disease': {'first_aid': 'Apply cold compress to relieve itching, keep skin clean and dry, avoid scratching to '
                               'prevent secondary bacterial infection.',
                  'lifestyle_guidance': 'Use hypoallergenic fragrance-free moisturizers and soaps, avoid known contact '
                                        'allergens.',
                  'specialist_referral': 'Dermatologist',
                  'treatment_options': ['Topical corticosteroids (Hydrocortisone / Betamethasone) for inflammatory '
                                        'dermatitis',
                                        'Topical antibiotics (Mupirocin) for impetigo',
                                        'Oral antihistamines for pruritus']},
 'tuberculosis': {'first_aid': 'Isolate in a well-ventilated room, wear surgical N95 mask, provide high-protein '
                               'nutrition, encourage cough hygiene.',
                  'lifestyle_guidance': 'Adhere strictly to medication schedule without missing doses, maintain room '
                                        'airflow, avoid close unmasked contact with vulnerable individuals.',
                  'specialist_referral': 'Pulmonologist / TB DOTS Clinic Specialist',
                  'treatment_options': ['Standard 6-month Directly Observed Therapy Short-course (DOTS): RIF, INH, '
                                        'PZA, EMB for 2 months, followed by RIF + INH for 4 months',
                                        'Pyridoxine (Vitamin B6) supplementation']},
 'typhoid': {'first_aid': 'Provide clean boiled water, light easily digestible diet, continuous tepid sponging for '
                          'fever, and monitor for abdominal guarding.',
             'lifestyle_guidance': 'Strict hand hygiene with soap and water before meals, consume bottled/boiled '
                                   'water, avoid raw street foods.',
             'specialist_referral': 'Gastroenterologist / Infectious Disease Specialist',
             'treatment_options': ['Ciprofloxacin, Azithromycin, or Ceftriaxone based on local antibiotic '
                                   'susceptibility',
                                   'High-calorie, low-roughage soft diet',
                                   'Fluid and electrolyte replacement']},
 'urinary_tract_infection': {'first_aid': 'Increase fluid intake (drink 2-3 liters of water daily), flush bladder '
                                          'frequently, apply warm heat pad to pelvis.',
                             'lifestyle_guidance': 'Urinate after intercourse, wipe front-to-back, avoid holding urine '
                                                   'for prolonged periods.',
                             'specialist_referral': 'Urologist / General Practitioner',
                             'treatment_options': ['First-line antibiotics: Nitrofurantoin or '
                                                   'Trimethoprim-Sulfamethoxazole for 3-5 days',
                                                   'Phenazopyridine for short-term bladder analgesia']}}


tests = {'allergies': [{'description': 'Identifies specific environmental or food triggers.',
                'name': 'Skin Prick Test / Serum Specific IgE (RAST)',
                'sample': 'Skin / Serum',
                'urgency': 'Routine'}],
 'anemia': [{'description': 'Evaluates Hemoglobin, Hematocrit, MCV, MCH.',
             'name': 'Complete Blood Count (CBC) with RBC Indices',
             'sample': 'Blood',
             'urgency': 'Routine'},
            {'description': 'Differentiates iron deficiency from other microcytic anemias.',
             'name': 'Serum Ferritin, Iron, and Total Iron-Binding Capacity (TIBC)',
             'sample': 'Serum',
             'urgency': 'Routine'}],
 'appendicitis': [{'description': 'Demonstrates non-compressible appendix > 6mm and appendicolith.',
                   'name': 'Abdominal Ultrasound / Contrast-Enhanced CT Abdomen',
                   'sample': 'Imaging',
                   'urgency': 'Emergency'},
                  {'description': 'Detects leukocytosis with left shift.',
                   'name': 'Full Blood Count (WBC with Differential)',
                   'sample': 'Blood',
                   'urgency': 'Emergency'}],
 'arthritis': [{'description': 'Evaluates for Gout.',
                'name': 'Serum Uric Acid Level',
                'sample': 'Serum',
                'urgency': 'Routine'},
               {'description': 'Serological diagnosis of Rheumatoid Arthritis.',
                'name': 'Rheumatoid Factor (RF) & Anti-CCP Antibodies',
                'sample': 'Serum',
                'urgency': 'Routine'}],
 'asthma': [{'description': 'Demonstrates reversible airway obstruction (FEV1 increase > 12%).',
             'name': 'Spirometry with Bronchodilator Reversibility',
             'sample': 'Physiological',
             'urgency': 'Routine'},
            {'description': 'Assesses acute airflow obstruction severity.',
             'name': 'Peak Expiratory Flow (PEF) Measurement',
             'sample': 'Physiological',
             'urgency': 'Urgent'}],
 'bronchitis': [{'description': 'Ensures adequate oxygenation.',
                 'name': 'Pulse Oximetry',
                 'sample': 'Physiological',
                 'urgency': 'Routine'}],
 'cholera': [{'description': 'Rapid detection of Vibrio cholerae darting motility.',
              'name': 'Stool Darkfield Microscopy / Crystal VC Dipstick',
              'sample': 'Stool',
              'urgency': 'Emergency'},
             {'description': 'Evaluates severe hypokalemia, hyponatremia, and prerenal azotemia.',
              'name': 'Serum Electrolytes and Renal Function',
              'sample': 'Serum',
              'urgency': 'Emergency'}],
 'covid19': [{'description': 'Molecular gold standard for viral RNA detection.',
              'name': 'SARS-CoV-2 RT-PCR Test',
              'sample': 'Nasopharyngeal Swab',
              'urgency': 'Urgent'},
             {'description': 'Point-of-care viral protein detection.',
              'name': 'Rapid Antigen Test (RAT)',
              'sample': 'Nasal Swab',
              'urgency': 'Urgent'}],
 'dehydration': [{'description': 'Assesses electrolyte imbalances and prerenal azotemia.',
                  'name': 'Serum Electrolytes, Urea, Creatinine',
                  'sample': 'Venous Blood',
                  'urgency': 'Urgent'}],
 'dengue': [{'description': 'Positive during days 1-7 of fever onset.',
             'name': 'Dengue NS1 Antigen Test',
             'sample': 'Serum',
             'urgency': 'Urgent'},
            {'description': 'Serological confirmation from day 5 onwards.',
             'name': 'Dengue IgM/IgG Antibodies',
             'sample': 'Serum',
             'urgency': 'Routine'},
            {'description': 'Monitors thrombocytopenia and hematocrit concentration.',
             'name': 'Full Blood Count (FBC/CBC)',
             'sample': 'Blood',
             'urgency': 'Urgent'}],
 'diabetes_mellitus': [{'description': 'Diagnostic if ≥ 126 mg/dL (7.0 mmol/L).',
                        'name': 'Fasting Plasma Glucose (FPG)',
                        'sample': 'Venous Blood',
                        'urgency': 'Routine'},
                       {'description': 'Evaluates 3-month average blood glucose control (Diagnostic if ≥ 6.5%).',
                        'name': 'Glycated Hemoglobin (HbA1c)',
                        'sample': 'Blood',
                        'urgency': 'Routine'},
                       {'description': 'Screens for early diabetic nephropathy.',
                        'name': 'Urine Microalbumin / Creatinine Ratio',
                        'sample': 'Urine',
                        'urgency': 'Routine'}],
 'food_poisoning': [{'description': 'Indicated if dysentery or severe prolonged symptoms.',
                     'name': 'Stool Culture for Salmonella, Shigella, Campylobacter, E. coli',
                     'sample': 'Stool',
                     'urgency': 'Routine'}],
 'hiv_screening': [{'description': 'Detects HIV p24 antigen and HIV-1/2 antibodies.',
                    'name': '4th Generation HIV 1/2 Ag/Ab Combo Immunoassay',
                    'sample': 'Serum',
                    'urgency': 'Routine'},
                   {'description': 'Confirms acute HIV before seroconversion.',
                    'name': 'HIV Viral Load PCR',
                    'sample': 'Plasma',
                    'urgency': 'Routine'}],
 'hypertension': [{'description': 'Gold standard for diagnosing sustained hypertension.',
                   'name': '24-Hour Ambulatory Blood Pressure Monitoring (ABPM)',
                   'sample': 'Physiological',
                   'urgency': 'Routine'},
                  {'description': 'Evaluates left ventricular hypertrophy or ischemia.',
                   'name': '12-Lead Electrocardiogram (ECG)',
                   'sample': 'Physiological',
                   'urgency': 'Routine'}],
 'influenza': [{'description': 'Differentiates Influenza A and B antigens.',
                'name': 'Rapid Influenza Diagnostic Test (RIDT)',
                'sample': 'Nasal/Throat Swab',
                'urgency': 'Routine'}],
 'kidney_disease': [{'description': 'Calculates estimated Glomerular Filtration Rate (eGFR).',
                     'name': 'Serum Creatinine and Blood Urea Nitrogen (BUN)',
                     'sample': 'Serum',
                     'urgency': 'Urgent'},
                    {'description': 'Detects proteinuria, hematuria, and cellular casts.',
                     'name': 'Urinalysis with Microscopic Examination',
                     'sample': 'Urine',
                     'urgency': 'Urgent'},
                    {'description': 'Assesses kidney size, parenchymal echogenicity, and obstruction.',
                     'name': 'Renal Ultrasound',
                     'sample': 'Imaging',
                     'urgency': 'Routine'}],
 'liver_disease': [{'description': 'Measures ALT, AST, Alkaline Phosphatase, Total Bilirubin, Albumin.',
                    'name': 'Liver Function Tests (LFTs)',
                    'sample': 'Serum',
                    'urgency': 'Urgent'},
                   {'description': 'Viral hepatitis screening.',
                    'name': 'Hepatitis B Surface Antigen (HBsAg) & Hep C Antibody',
                    'sample': 'Serum',
                    'urgency': 'Routine'},
                   {'description': 'Evaluates liver echotexture, fatty infiltration, or focal lesions.',
                    'name': 'Abdominal Ultrasound',
                    'sample': 'Imaging',
                    'urgency': 'Routine'}],
 'malaria': [{'description': 'Detects Plasmodium falciparum / vivax specific antigens.',
              'name': 'Rapid Diagnostic Test (RDT) for Malaria',
              'sample': 'Blood',
              'urgency': 'Urgent'},
             {'description': 'Gold standard for identifying Plasmodium species and parasite density.',
              'name': 'Thick and Thin Blood Smear Microscopy',
              'sample': 'Capillary/Venous Blood',
              'urgency': 'Urgent'}],
 'meningitis': [{'description': 'Evaluates CSF pressure, cell count, protein, glucose, Gram stain, and culture.',
                 'name': 'Lumbar Puncture & Cerebrospinal Fluid (CSF) Analysis',
                 'sample': 'CSF',
                 'urgency': 'Emergency'},
                {'description': 'Identifies bacteremia prior to antibiotics.',
                 'name': 'Blood Cultures x2',
                 'sample': 'Blood',
                 'urgency': 'Emergency'}],
 'migraine': [{'description': 'Indicated ONLY if abnormal neurological exam or thunderclap onset.',
               'name': 'Brain MRI / CT Head',
               'sample': 'Imaging',
               'urgency': 'Routine'}],
 'peptic_ulcer': [{'description': 'Non-invasive detection of active H. pylori infection.',
                   'name': 'H. Pylori Stool Antigen / Urea Breath Test',
                   'sample': 'Stool / Breath',
                   'urgency': 'Routine'},
                  {'description': 'Direct visualization and biopsy of mucosal ulceration.',
                   'name': 'Esophagogastroduodenoscopy (EGD)',
                   'sample': 'Endoscopy',
                   'urgency': 'Urgent'}],
 'pneumonia': [{'description': 'Identifies lobar or interstitial pulmonary infiltrates/consolidation.',
                'name': 'Chest X-Ray (PA and Lateral Views)',
                'sample': 'Imaging',
                'urgency': 'Urgent'},
               {'description': 'Determines causative bacterial pathogen and antibiotic sensitivities.',
                'name': 'Sputum Gram Stain and Culture',
                'sample': 'Sputum',
                'urgency': 'Routine'},
               {'description': 'Evaluates hypoxemia and acid-base balance.',
                'name': 'Pulse Oximetry / Arterial Blood Gas (ABG)',
                'sample': 'Arterial Blood',
                'urgency': 'Urgent'}],
 'sexually_transmitted_infection': [{'description': 'High sensitivity nucleic acid amplification test.',
                                     'name': 'NAAT / PCR Swab for Neisseria gonorrhoeae & Chlamydia trachomatis',
                                     'sample': 'Genital Swab / First-catch Urine',
                                     'urgency': 'Routine'},
                                    {'description': 'Syphilis screening.',
                                     'name': 'VDRL / RPR & Treponema Serology',
                                     'sample': 'Serum',
                                     'urgency': 'Routine'}],
 'sinusitis': [{'description': 'Indicated if complicated or refractory to treatment.',
                'name': 'CT Scan of Paranasal Sinuses',
                'sample': 'Imaging',
                'urgency': 'Routine'}],
 'skin_disease': [{'description': 'Rule out fungal infection.',
                   'name': 'Skin Lesion Potassium Hydroxide (KOH) Preparation',
                   'sample': 'Skin Scraping',
                   'urgency': 'Routine'},
                  {'description': 'Identifies Staphylococcus aureus or Streptococcus pyogenes.',
                   'name': 'Wound Swab Bacterial Culture',
                   'sample': 'Pus Swab',
                   'urgency': 'Routine'}],
 'tuberculosis': [{'description': 'Rapid molecular detection of M. tuberculosis and Rifampicin resistance.',
                   'name': 'GeneXpert MTB/RIF Ultra PCR',
                   'sample': 'Sputum',
                   'urgency': 'Urgent'},
                  {'description': 'Zieht-Neelsen staining for tubercle bacilli.',
                   'name': 'Acid-Fast Bacilli (AFB) Sputum Microscopy',
                   'sample': 'Sputum',
                   'urgency': 'Routine'},
                  {'description': 'Shows apical cavitation or hilar lymphadenopathy.',
                   'name': 'Chest Radiograph',
                   'sample': 'Imaging',
                   'urgency': 'Routine'}],
 'typhoid': [{'description': 'Definitive diagnostic test during 1st week of fever.',
              'name': 'Blood Culture for Salmonella Typhi',
              'sample': 'Blood',
              'urgency': 'Urgent'},
             {'description': 'Serological test for O and H antibodies.',
              'name': 'Widal Test / Typhidot IgM',
              'sample': 'Serum',
              'urgency': 'Routine'}],
 'urinary_tract_infection': [{'description': 'Rapid point-of-care UTI confirmation.',
                              'name': 'Urinalysis Dipstick (Leukocyte Esterase & Nitrite)',
                              'sample': 'Midstream Urine',
                              'urgency': 'Routine'},
                             {'description': 'Identifies causative uropathogen and antibiotic susceptibilities.',
                              'name': 'Urine Microscopy, Culture and Sensitivity',
                              'sample': 'Urine',
                              'urgency': 'Routine'}]}


contraindications = [{'condition': 'pregnancy',
  'prohibited_medications': ['Artemether-Lumefantrine (1st trimester)',
                             'Ciprofloxacin',
                             'Doxycycline',
                             'Metformin (relative)',
                             'ACE Inhibitors',
                             'ARBs'],
  'safe_alternatives': ['Quinine + Clindamycin (1st trimester Malaria)', 'Amoxicillin', 'Methyldopa', 'Insulin'],
  'warning': 'CRITICAL: Patient is pregnant. Avoid fluoroquinolones, tetracyclines, and RAAS blockers.'},
 {'condition': 'renal_impairment',
  'prohibited_medications': ['High-dose NSAIDs (Ibuprofen, Naproxen, Diclofenac)',
                             'Metformin (eGFR < 30)',
                             'Aminoglycosides (Gentamicin) without therapeutic drug monitoring'],
  'safe_alternatives': ['Acetaminophen / Paracetamol', 'Insulin', 'Dose-adjusted beta-lactams'],
  'warning': 'CRITICAL: Renal insufficiency detected. Avoid nephrotoxic agents and adjust renally cleared drug '
             'dosages.'},
 {'condition': 'hepatic_impairment',
  'prohibited_medications': ['High-dose Acetaminophen / Paracetamol (> 2g/day)',
                             'Statin therapy',
                             'Isoniazid (severe liver damage)'],
  'safe_alternatives': ['Low-dose Paracetamol max 2g/day', 'Topical analgesics'],
  'warning': 'WARNING: Hepatic dysfunction detected. Limit acetaminophen dose to maximum 2g in 24 hours.'},
 {'condition': 'nsaid_allergy',
  'prohibited_medications': ['Aspirin', 'Ibuprofen', 'Naproxen', 'Diclofenac', 'Ketorolac'],
  'safe_alternatives': ['Acetaminophen', 'Tramadol'],
  'warning': 'ALLERGY ALERT: Avoid all NSAIDs and Aspirin formulations.'},
 {'condition': 'penicillin_allergy',
  'prohibited_medications': ['Amoxicillin', 'Ampicillin', 'Penicillin V/G', 'Piperacillin-Tazobactam'],
  'safe_alternatives': ['Macrolides (Azithromycin, Erythromycin)', 'Fluoroquinolones', 'Vancomycin'],
  'warning': 'ALLERGY ALERT: Patient has documented Penicillin allergy.'}]


triage_rules = [{'action': 'Dispatch immediate emergency medical services (EMS) or proceed to the nearest Emergency Department '
            'immediately.',
  'badge': 'EMERGENCY - IMMEDIATE MEDICAL INTERVENTION',
  'color': '#DC2626',
  'criteria': ['Inability to breathe, severe respiratory distress, or cyanosis',
               'Altered mental status, coma, or active seizures',
               'Systolic BP > 180 mmHg or < 90 mmHg',
               'Signs of acute surgical abdomen (migrating RLQ pain with rebound tenderness)',
               'Profuse rice-water diarrhea with hypovolemic shock',
               'Suspected Acute Meningitis (high fever + nuchal rigidity + photophobia)'],
  'level': 'Emergency'},
 {'action': 'Schedule an urgent outpatient clinic appointment or visit an urgent care center within 12 to 24 hours.',
  'badge': 'URGENT - MEDICAL EVALUATION WITHIN 12-24 HOURS',
  'color': '#F59E0B',
  'criteria': ['Sustained high fever (> 39.0°C) lasting > 3 days',
               'Jaundice or dark tea-colored urine',
               'Productive cough with chest pain or hemoptysis',
               'Severe acute vomiting preventing oral fluid intake',
               'Moderate dehydration or oliguria'],
  'level': 'Urgent'},
 {'action': 'Follow supportive self-care recommendations and consult a general practitioner for routine evaluation.',
  'badge': 'ROUTINE / MILD - OUTPATIENT CONSULTATION',
  'color': '#10B981',
  'criteria': ['Mild upper respiratory symptoms without dyspnea',
               'Uncomplicated rash without fever',
               'Mild episodic tension headache or chronic joint stiffness',
               'Routine health screening or minor localized discomfort'],
  'level': 'Normal'}]

