"""Symptom metadata, alias resolution, and question generation."""

symptoms_dict = {'abdominal_pain': {'category': 'Gastrointestinal',
                    'follow_ups': ['abdominal_pain_location'],
                    'id': 'abdominal_pain',
                    'name': 'Abdominal Pain',
                    'question': 'Is there pain or tenderness in the abdomen?',
                    'type': 'boolean'},
 'abdominal_pain_location': {'category': 'Gastrointestinal',
                             'id': 'abdominal_pain_location',
                             'name': 'Abdominal Pain Location',
                             'options': ['Epigastric (upper center)',
                                         'Right lower quadrant (RLQ)',
                                         'Right upper quadrant (RUQ)',
                                         'Generalized diffuse cramps',
                                         'Suprapubic (lower pelvic)'],
                             'question': 'Where is the abdominal pain primarily located?',
                             'type': 'single_choice'},
 'abdominal_swelling': {'category': 'Gastrointestinal',
                        'id': 'abdominal_swelling',
                        'name': 'Abdominal Swelling',
                        'question': 'Is the abdomen noticeably swollen or distended?',
                        'type': 'boolean'},
 'abnormal_bleeding': {'category': 'Emergency',
                       'id': 'abnormal_bleeding',
                       'name': 'Abnormal Bleeding',
                       'question': 'Is there unusual bleeding or easy bruising?',
                       'type': 'boolean'},
 'abscess': {'category': 'Dermatological',
             'id': 'abscess',
             'name': 'Abscess / Localized Pus Collection',
             'question': 'Is there a painful, swollen lump that may be an abscess?',
             'type': 'boolean'},
 'altered_consciousness_dka': {'category': 'Emergency',
                               'id': 'altered_consciousness_dka',
                               'name': 'Altered Consciousness with Possible Hyperglycaemia',
                               'question': 'Is there confusion, drowsiness, or reduced consciousness?',
                               'type': 'boolean'},
 'altered_mental_status': {'category': 'Neurological',
                           'id': 'altered_mental_status',
                           'name': 'Confusion / Altered Consciousness',
                           'question': 'Is the patient confused, lethargic, delirious, or unusually disoriented?',
                           'type': 'boolean'},
 'anuria': {'category': 'Emergency renal',
            'id': 'anuria',
            'name': 'No Urine Output',
            'question': 'Has urine output stopped?',
            'type': 'boolean'},
 'anxiety': {'category': 'General',
             'id': 'anxiety',
             'name': 'Anxiety / Panic',
             'question': 'Is the patient experiencing marked anxiety or panic with the symptoms?',
             'type': 'boolean'},
 'ataxia': {'category': 'Neurological',
            'id': 'ataxia',
            'name': 'Uncoordinated Movement / Ataxia',
            'question': 'Is the patient having trouble with balance or coordinated movement?',
            'type': 'boolean'},
 'back_pain': {'category': 'Musculoskeletal',
               'id': 'back_pain',
               'name': 'Back Pain',
               'question': 'Is there new back pain?',
               'type': 'boolean'},
 'bloating': {'category': 'Gastrointestinal',
              'id': 'bloating',
              'name': 'Abdominal Bloating',
              'question': 'Is there troublesome abdominal fullness or bloating?',
              'type': 'boolean'},
 'blood_in_urine': {'category': 'Urological',
                    'id': 'blood_in_urine',
                    'name': 'Blood in Urine',
                    'question': 'Has there been visible blood in the urine?',
                    'type': 'boolean'},
 'blood_in_vomit_stool': {'category': 'Emergency gastrointestinal',
                          'id': 'blood_in_vomit_stool',
                          'name': 'Blood in Vomit or Stool',
                          'question': 'Has there been blood in vomit or stool?',
                          'type': 'boolean'},
 'bloody_stool': {'category': 'Emergency gastrointestinal',
                  'id': 'bloody_stool',
                  'name': 'Bloody Stool',
                  'question': 'Is there blood in the stool?',
                  'type': 'boolean'},
 'blurred_vision': {'category': 'Neurological',
                    'id': 'blurred_vision',
                    'name': 'Blurred Vision',
                    'question': 'Has the patient noticed blurred vision?',
                    'type': 'boolean'},
 'bone_pain': {'category': 'Musculoskeletal',
               'id': 'bone_pain',
               'name': 'Bone Pain',
               'question': 'Is there significant bone pain?',
               'type': 'boolean'},
 'calf_pain': {'category': 'Musculoskeletal',
               'id': 'calf_pain',
               'name': 'Calf Pain',
               'question': 'Is there pain in the calf muscles?',
               'type': 'boolean'},
 'calf_swelling': {'category': 'Musculoskeletal',
                   'id': 'calf_swelling',
                   'name': 'Calf Swelling',
                   'question': 'Is there swelling of the calf or lower leg?',
                   'type': 'boolean'},
 'chest_pain': {'category': 'Cardiorespiratory',
                'follow_ups': ['chest_pain_character'],
                'id': 'chest_pain',
                'name': 'Chest Pain / Discomfort',
                'question': 'Is the patient feeling pain, tightness, or pressure in the chest?',
                'type': 'boolean'},
 'chest_pain_character': {'category': 'Cardiorespiratory',
                          'id': 'chest_pain_character',
                          'name': 'Chest Pain Characteristics',
                          'options': ['Sharp pleuritic pain on deep breath',
                                      'Substernal burning pain',
                                      'Tight squeezing pressure',
                                      'Localized muscle tenderness'],
                          'question': 'Describe the chest pain:',
                          'type': 'single_choice'},
 'chills': {'category': 'Systemic',
            'id': 'chills',
            'name': 'Chills / Rigors',
            'question': 'Has the patient had shaking chills or rigors?',
            'type': 'boolean'},
 'claudication': {'category': 'Vascular',
                  'id': 'claudication',
                  'name': 'Leg Pain on Walking (Claudication)',
                  'question': 'Does the patient get cramp-like leg pain when walking that eases with rest?',
                  'type': 'boolean'},
 'cloudy_urine': {'category': 'Urological',
                  'id': 'cloudy_urine',
                  'name': 'Cloudy Urine',
                  'question': 'Does the urine look cloudy?',
                  'type': 'boolean'},
 'coagulopathy_bleeding': {'category': 'Emergency',
                           'id': 'coagulopathy_bleeding',
                           'name': 'Unexpected Bleeding',
                           'question': 'Is there unexpected bleeding or extensive bruising?',
                           'type': 'boolean'},
 'cold_clammy_skin': {'category': 'Emergency',
                      'id': 'cold_clammy_skin',
                      'name': 'Cold, Clammy Skin',
                      'question': 'Is the skin pale, cold, or clammy?',
                      'type': 'boolean'},
 'cold_hands_feet': {'category': 'Emergency',
                     'id': 'cold_hands_feet',
                     'name': 'Cold Hands or Feet',
                     'question': 'Are the hands or feet unusually cold?',
                     'type': 'boolean'},
 'coma': {'category': 'Emergency',
          'id': 'coma',
          'name': 'Coma / Unresponsiveness',
          'question': 'Is the patient unresponsive?',
          'type': 'boolean'},
 'confusion': {'category': 'Emergency neurological',
               'id': 'confusion',
               'name': 'Confusion',
               'question': 'Is the patient newly confused or disoriented?',
               'type': 'boolean'},
 'confusion_lethargy': {'category': 'Emergency',
                        'id': 'confusion_lethargy',
                        'name': 'Confusion or Marked Lethargy',
                        'question': 'Is the patient newly confused or unusually difficult to rouse?',
                        'type': 'boolean'},
 'constipation': {'category': 'Gastrointestinal',
                  'id': 'constipation',
                  'name': 'Constipation',
                  'question': 'Has the patient had constipation or difficulty passing stool?',
                  'type': 'boolean'},
 'cough': {'category': 'Respiratory',
           'follow_ups': ['cough_type', 'cough_duration', 'hemoptysis'],
           'id': 'cough',
           'name': 'Cough',
           'question': 'Is the patient suffering from a cough?',
           'type': 'boolean'},
 'cough_type': {'category': 'Respiratory',
                'id': 'cough_type',
                'name': 'Cough Type',
                'options': ['Dry cough',
                            'Productive with clear/white sputum',
                            'Productive with yellow/green purulent sputum',
                            'Coughing up blood (Hemoptysis)'],
                'question': 'Is the cough dry or productive (with sputum)?',
                'type': 'single_choice'},
 'cyanosis': {'category': 'Emergency respiratory',
              'id': 'cyanosis',
              'name': 'Blue or Grey Lips/Skin',
              'question': 'Do the lips, face, or nail beds look blue or grey?',
              'type': 'boolean'},
 'dark_urine': {'category': 'Hepatic',
                'id': 'dark_urine',
                'name': 'Dark Urine',
                'question': 'Is the urine noticeably dark, tea-colored, or brown?',
                'type': 'boolean'},
 'dehydration': {'category': 'Fluid balance',
                 'id': 'dehydration',
                 'name': 'Signs of Dehydration',
                 'question': 'Is there marked thirst, dry mouth, or reduced urine after fluid loss?',
                 'type': 'boolean'},
 'delirium': {'category': 'Emergency neurological',
              'id': 'delirium',
              'name': 'Delirium',
              'question': 'Is there sudden severe confusion, agitation, or disorientation?',
              'type': 'boolean'},
 'diarrhea': {'category': 'Gastrointestinal',
              'follow_ups': ['diarrhea_type'],
              'id': 'diarrhea',
              'name': 'Diarrhea / Loose Stools',
              'question': 'Is the patient having frequent loose or watery bowel movements?',
              'type': 'boolean'},
 'diarrhea_type': {'category': 'Gastrointestinal',
                   'id': 'diarrhea_type',
                   'name': 'Diarrhea Appearance',
                   'options': ['Profuse rice-water fluid',
                               'Watery without blood',
                               'Bloody/mucoid stool',
                               'Dark black tarry stool (Melena)'],
                   'question': 'Describe the diarrhea stool:',
                   'type': 'single_choice'},
 'difficulty_breathing': {'category': 'Emergency respiratory',
                          'id': 'difficulty_breathing',
                          'name': 'Difficulty Breathing',
                          'question': 'Is breathing difficult, especially at rest?',
                          'type': 'boolean'},
 'diffuse_pain': {'category': 'General',
                  'id': 'diffuse_pain',
                  'name': 'Widespread Pain',
                  'question': 'Is pain widespread rather than localized?',
                  'type': 'boolean'},
 'diplopia': {'category': 'Neurological',
              'id': 'diplopia',
              'name': 'Double Vision (Diplopia)',
              'question': 'Is the patient experiencing double vision?',
              'type': 'boolean'},
 'dizziness': {'category': 'Neurological',
               'id': 'dizziness',
               'name': 'Dizziness / Lightheadedness',
               'question': 'Does the patient feel dizzy, faint, or lightheaded?',
               'type': 'boolean'},
 'double_vision': {'category': 'Neurological',
                   'id': 'double_vision',
                   'name': 'Double Vision',
                   'question': 'Are objects seen as doubled or overlapped?',
                   'type': 'boolean'},
 'dry_cough': {'category': 'Respiratory',
               'id': 'dry_cough',
               'name': 'Dry Cough',
               'question': 'Is the cough mainly dry, without phlegm?',
               'type': 'boolean'},
 'dry_mouth_mucosa': {'category': 'Fluid balance',
                      'id': 'dry_mouth_mucosa',
                      'name': 'Dry Mouth / Mucosa',
                      'question': 'Is the mouth or tongue unusually dry?',
                      'type': 'boolean'},
 'dysphagia': {'category': 'ENT',
               'id': 'dysphagia',
               'name': 'Difficulty Swallowing (Dysphagia)',
               'question': 'Is the patient having trouble swallowing or pain when swallowing?',
               'type': 'boolean'},
 'dyspnea_severity': {'category': 'Respiratory',
                      'id': 'dyspnea_severity',
                      'name': 'Dyspnea Severity',
                      'options': ['Only on strenuous exertion',
                                  'On mild walking/activity',
                                  'At rest or lying flat',
                                  'Sudden asphyxiating onset'],
                      'question': 'When does shortness of breath occur?',
                      'type': 'single_choice'},
 'dysuria': {'category': 'Urological',
             'id': 'dysuria',
             'name': 'Painful Urination (Dysuria)',
             'question': 'Is there burning or discomfort during urination?',
             'type': 'boolean'},
 'ear_discharge': {'category': 'ENT',
                   'id': 'ear_discharge',
                   'name': 'Ear Discharge',
                   'question': 'Is there any fluid or pus coming from the ear?',
                   'type': 'boolean'},
 'ear_pain': {'category': 'ENT',
              'id': 'ear_pain',
              'name': 'Ear Pain / Otalgia',
              'question': 'Is there ear pain or discomfort?',
              'type': 'boolean'},
 'early_satiety': {'category': 'Gastrointestinal',
                   'id': 'early_satiety',
                   'name': 'Early Satiety',
                   'question': 'Does the patient feel full after eating only a small amount?',
                   'type': 'boolean'},
 'easy_bruising': {'category': 'Hematologic',
                   'id': 'easy_bruising',
                   'name': 'Easy Bruising',
                   'question': 'Has the patient developed unusual or easy bruising?',
                   'type': 'boolean'},
 'eye_pain': {'category': 'Ophthalmic',
              'id': 'eye_pain',
              'name': 'Eye Pain',
              'question': 'Is the patient experiencing eye pain?',
              'type': 'boolean'},
 'facial_droop': {'category': 'Neurological',
                  'id': 'facial_droop',
                  'name': 'Facial Droop / Asymmetry',
                  'question': 'Is one side of the face drooping or asymmetric?',
                  'type': 'boolean'},
 'facial_flushing': {'category': 'Dermatological',
                     'id': 'facial_flushing',
                     'name': 'Facial Flushing',
                     'question': 'Has the face become unusually red or flushed?',
                     'type': 'boolean'},
 'facial_swelling': {'category': 'Allergy',
                     'id': 'facial_swelling',
                     'name': 'Facial Swelling',
                     'question': 'Is there swelling of the face, lips, tongue, or throat?',
                     'type': 'boolean'},
 'fatigue': {'category': 'Systemic',
             'id': 'fatigue',
             'name': 'Fatigue / Malaise',
             'question': 'Is there unusual tiredness, weakness, or feeling unwell?',
             'type': 'boolean'},
 'fever': {'category': 'Systemic',
           'follow_ups': ['fever_degree', 'fever_pattern'],
           'id': 'fever',
           'name': 'Fever / Elevated Body Temperature',
           'question': 'Does the patient currently have a fever or elevated body temperature?',
           'type': 'boolean_with_details'},
 'fever_degree': {'category': 'Systemic',
                  'id': 'fever_degree',
                  'name': 'Measured Body Temperature',
                  'normal_range': '36.5 - 37.5',
                  'question': 'What is the measured body temperature in °C?',
                  'type': 'number',
                  'unit': '°C'},
 'fever_pattern': {'category': 'Systemic',
                   'id': 'fever_pattern',
                   'name': 'Fever Pattern',
                   'options': ['Continuous high fever',
                               'Periodic chills & fever spikes',
                               'Low grade evening fever',
                               'Sudden high spike'],
                   'question': 'How would you describe the fever pattern?',
                   'type': 'single_choice'},
 'flank_pain': {'category': 'Renal',
                'id': 'flank_pain',
                'name': 'Flank / Side Pain',
                'question': 'Is there pain in the side or back below the ribs?',
                'type': 'boolean'},
 'fluid_accumulation': {'category': 'Fluid balance',
                        'id': 'fluid_accumulation',
                        'name': 'Fluid Accumulation / Edema',
                        'question': 'Is there swelling or fluid buildup in the abdomen, lungs, or legs?',
                        'type': 'boolean'},
 'gastrointestinal_bleeding': {'category': 'Emergency gastrointestinal',
                               'id': 'gastrointestinal_bleeding',
                               'name': 'Gastrointestinal Bleeding',
                               'question': 'Has there been black stool, blood in stool, or vomiting blood?',
                               'type': 'boolean'},
 'genital_itching': {'category': 'Metabolic',
                     'id': 'genital_itching',
                     'name': 'Genital Itching',
                     'question': 'Is there persistent genital itching?',
                     'type': 'boolean'},
 'gum_bleeding': {'category': 'Hematologic',
                  'id': 'gum_bleeding',
                  'name': 'Gum Bleeding',
                  'question': 'Has there been bleeding from the gums?',
                  'type': 'boolean'},
 'headache': {'category': 'Neurological',
              'follow_ups': ['headache_location_type'],
              'id': 'headache',
              'name': 'Headache',
              'question': 'Is the patient experiencing headaches?',
              'type': 'boolean'},
 'headache_location_type': {'category': 'Neurological',
                            'id': 'headache_location_type',
                            'name': 'Headache Type',
                            'options': ['Frontal/facial pressure pain',
                                        'Unilateral pulsating pain with nausea',
                                        'Diffusely severe with stiff neck',
                                        'Occipital dull pain'],
                            'question': 'Where and how is the headache felt?',
                            'type': 'single_choice'},
 'hematemesis': {'category': 'Emergency gastrointestinal',
                 'id': 'hematemesis',
                 'name': 'Vomiting Blood',
                 'question': 'Has the patient vomited blood or coffee-ground material?',
                 'type': 'boolean'},
 'hemiparesis': {'category': 'Neurological',
                 'id': 'hemiparesis',
                 'name': 'Weakness on One Side (Hemiparesis)',
                 'question': 'Is there weakness affecting one side of the body?',
                 'type': 'boolean'},
 'hemoptysis': {'category': 'Respiratory',
                'id': 'hemoptysis',
                'name': 'Coughing Blood',
                'question': 'Has the patient coughed up blood?',
                'type': 'boolean'},
 'hepatic_encephalopathy': {'category': 'Emergency hepatic',
                            'id': 'hepatic_encephalopathy',
                            'name': 'Confusion with Liver Disease',
                            'question': 'Is there new confusion, unusual sleepiness, or personality change?',
                            'type': 'boolean'},
 'high_fever_pyelonephritis': {'category': 'Emergency urological',
                               'id': 'high_fever_pyelonephritis',
                               'name': 'High Fever with Urinary Symptoms',
                               'question': 'Is there high fever or shaking chills with urinary symptoms?',
                               'type': 'boolean'},
 'hoarseness': {'category': 'ENT',
                'id': 'hoarseness',
                'name': 'Hoarseness / Voice Change',
                'question': "Has the patient's voice become hoarse or changed?",
                'type': 'boolean'},
 'hot_red_single_septic_joint': {'category': 'Emergency musculoskeletal',
                                 'id': 'hot_red_single_septic_joint',
                                 'name': 'Hot Red Single Joint',
                                 'question': 'Is one joint suddenly hot, red, swollen, and very painful?',
                                 'type': 'boolean'},
 'hypotension': {'category': 'Emergency',
                 'id': 'hypotension',
                 'name': 'Possible Low Blood Pressure',
                 'question': 'Has there been fainting, collapse, or documented very low blood pressure?',
                 'type': 'boolean'},
 'hypovolemic_shock': {'category': 'Emergency',
                       'id': 'hypovolemic_shock',
                       'name': 'Possible Shock from Fluid Loss',
                       'question': 'Is there collapse, very weak pulse, cold clammy skin, or very little urine?',
                       'type': 'boolean'},
 'hypoxia': {'category': 'Emergency respiratory',
             'id': 'hypoxia',
             'name': 'Low Oxygen Level',
             'question': 'Is oxygen saturation low if measured, or are there blue lips/marked breathlessness?',
             'type': 'boolean'},
 'inability_to_keep_fluids_down_24h': {'category': 'Emergency gastrointestinal',
                                       'id': 'inability_to_keep_fluids_down_24h',
                                       'name': 'Unable to Keep Fluids Down',
                                       'question': 'Has vomiting prevented keeping fluids down?',
                                       'type': 'boolean'},
 'inability_to_pass_gas': {'category': 'Gastrointestinal',
                           'id': 'inability_to_pass_gas',
                           'name': 'Unable to Pass Gas',
                           'question': 'Is the patient unable to pass gas?',
                           'type': 'boolean'},
 'inability_to_speak_full_sentences': {'category': 'Emergency respiratory',
                                       'id': 'inability_to_speak_full_sentences',
                                       'name': 'Cannot Speak Full Sentences',
                                       'question': 'Is breathlessness preventing speaking full sentences?',
                                       'type': 'boolean'},
 'incontinence': {'category': 'Urological',
                  'id': 'incontinence',
                  'name': 'Urinary Incontinence',
                  'question': 'Is the patient unable to control their bladder or have accidental urine leakage?',
                  'type': 'boolean'},
 'insomnia': {'category': 'Psychological',
              'id': 'insomnia',
              'name': 'Insomnia / Poor Sleep',
              'question': 'Is the patient having trouble falling or staying asleep?',
              'type': 'boolean'},
 'itching': {'category': 'General',
             'id': 'itching',
             'name': 'Generalized Itching',
             'question': 'Is there persistent generalized itching?',
             'type': 'boolean'},
 'jaundice': {'category': 'Hepatic',
              'id': 'jaundice',
              'name': 'Jaundice (Yellowing of Eyes/Skin)',
              'question': 'Is there visible yellowing of the sclera (eyes) or skin?',
              'type': 'boolean'},
 'joint_pain': {'category': 'Musculoskeletal',
                'id': 'joint_pain',
                'name': 'Joint Pain / Arthralgia',
                'question': 'Are joints painful, swollen, or stiff?',
                'type': 'boolean'},
 'joint_redness': {'category': 'Musculoskeletal',
                   'id': 'joint_redness',
                   'name': 'Joint Redness',
                   'question': 'Is a painful joint visibly red?',
                   'type': 'boolean'},
 'joint_stiffness': {'category': 'Musculoskeletal',
                     'id': 'joint_stiffness',
                     'name': 'Joint Stiffness',
                     'question': 'Are joints stiff, especially after rest or in the morning?',
                     'type': 'boolean'},
 'joint_swelling': {'category': 'Musculoskeletal',
                    'id': 'joint_swelling',
                    'name': 'Joint Swelling',
                    'question': 'Is any joint visibly swollen?',
                    'type': 'boolean'},
 'lethargy': {'category': 'Systemic',
              'id': 'lethargy',
              'name': 'Lethargy / Marked Fatigue',
              'question': 'Is the patient unusually sleepy, sluggish, or difficult to rouse?',
              'type': 'boolean'},
 'loss_of_appetite': {'category': 'Gastrointestinal',
                      'id': 'loss_of_appetite',
                      'name': 'Loss of Appetite',
                      'question': 'Has the patient had a reduced appetite?',
                      'type': 'boolean'},
 'loss_of_taste_smell': {'category': 'Respiratory',
                         'id': 'loss_of_taste_smell',
                         'name': 'New Loss of Taste or Smell',
                         'question': 'Has there been a new loss or marked change in taste or smell?',
                         'type': 'boolean'},
 'lymphadenopathy': {'category': 'Systemic',
                     'id': 'lymphadenopathy',
                     'name': 'Swollen Lymph Nodes / Lymphadenopathy',
                     'question': 'Are lymph nodes (neck/armpit/groin) enlarged or tender?',
                     'type': 'boolean'},
 'massive_hemoptysis': {'category': 'Emergency respiratory',
                        'id': 'massive_hemoptysis',
                        'name': 'Large-volume Coughing of Blood',
                        'question': 'Has the patient coughed up more than streaks of blood?',
                        'type': 'boolean'},
 'melena': {'category': 'Emergency gastrointestinal',
            'id': 'melena',
            'name': 'Black Tarry Stool',
            'question': 'Are stools black and tarry?',
            'type': 'boolean'},
 'mucosal_bleeding': {'category': 'Hematologic',
                      'id': 'mucosal_bleeding',
                      'name': 'Mucosal Bleeding',
                      'question': 'Is there bleeding from the gums, nose, or other mucosal surfaces?',
                      'type': 'boolean'},
 'muscle_cramps': {'category': 'Fluid balance',
                   'id': 'muscle_cramps',
                   'name': 'Muscle Cramps',
                   'question': 'Has the patient had muscle cramps?',
                   'type': 'boolean'},
 'muscle_pain': {'category': 'Musculoskeletal',
                 'id': 'muscle_pain',
                 'name': 'Muscle Pain / Myalgia',
                 'question': 'Does the patient have muscle aches or body pain?',
                 'type': 'boolean'},
 'muscle_weakness': {'category': 'Musculoskeletal',
                     'id': 'muscle_weakness',
                     'name': 'Muscle Weakness',
                     'question': 'Is there noticeable new weakness of muscles?',
                     'type': 'boolean'},
 'nasal_congestion': {'category': 'Respiratory',
                      'id': 'nasal_congestion',
                      'name': 'Nasal Congestion',
                      'question': 'Is the nose blocked or congested?',
                      'type': 'boolean'},
 'nausea_vomiting': {'category': 'Gastrointestinal',
                     'follow_ups': ['vomiting_frequency'],
                     'id': 'nausea_vomiting',
                     'name': 'Nausea / Vomiting',
                     'question': 'Has the patient had nausea or vomiting episodes?',
                     'type': 'boolean'},
 'night_sweats': {'category': 'Systemic',
                  'id': 'night_sweats',
                  'name': 'Night Sweats',
                  'question': 'Has the patient had drenching night sweats?',
                  'type': 'boolean'},
 'nocturia': {'category': 'Urological',
              'id': 'nocturia',
              'name': 'Night-time Urination (Nocturia)',
              'question': 'Does the patient wake at night to urinate frequently?',
              'type': 'boolean'},
 'nose_bleeding': {'category': 'Hematologic',
                   'id': 'nose_bleeding',
                   'name': 'Nose Bleeding',
                   'question': 'Has there been bleeding from the nose?',
                   'type': 'boolean'},
 'nuchal_rigidity': {'category': 'Neurological',
                     'id': 'nuchal_rigidity',
                     'name': 'Neck Stiffness / Nuchal Rigidity',
                     'question': 'Does the patient experience pain or resistance when trying to touch their chin to '
                                 'chest?',
                     'type': 'boolean'},
 'numbness': {'category': 'Neurological',
              'id': 'numbness',
              'name': 'Numbness or Loss of Sensation',
              'question': 'Is there any new numbness or loss of sensation in limbs or face?',
              'type': 'boolean'},
 'oliguria_anuria': {'category': 'Renal',
                     'id': 'oliguria_anuria',
                     'name': 'Very Little or No Urine',
                     'question': 'Has urine output become much lower than usual or stopped?',
                     'type': 'boolean'},
 'orthopnea': {'category': 'Respiratory',
               'id': 'orthopnea',
               'name': 'Orthopnea (Breathlessness when Lying Flat)',
               'question': 'Does the patient have more breathlessness when lying flat?',
               'type': 'boolean'},
 'oxygen_saturation_below_94': {'category': 'Emergency respiratory',
                                'id': 'oxygen_saturation_below_94',
                                'name': 'Oxygen Saturation Below 94%',
                                'question': 'If measured, is oxygen saturation below 94%?',
                                'type': 'boolean'},
 'pale_stools': {'category': 'Hepatic',
                 'id': 'pale_stools',
                 'name': 'Pale Stools',
                 'question': 'Are stools unusually pale or clay-coloured?',
                 'type': 'boolean'},
 'pallor': {'category': 'Hematologic',
            'id': 'pallor',
            'name': 'Pale Skin or Inner Eyelids',
            'question': 'Has the patient appeared unusually pale?',
            'type': 'boolean'},
 'palpitations': {'category': 'Cardiovascular',
                  'id': 'palpitations',
                  'name': 'Palpitations',
                  'question': 'Does the patient feel a racing, pounding, or irregular heartbeat?',
                  'type': 'boolean'},
 'paresthesia': {'category': 'Neurological',
                 'id': 'paresthesia',
                 'name': 'Pins and Needles / Paresthesia',
                 'question': "Are there tingling or 'pins and needles' sensations?",
                 'type': 'boolean'},
 'paroxysmal_nocturnal_dyspnea': {'category': 'Respiratory',
                                  'id': 'paroxysmal_nocturnal_dyspnea',
                                  'name': 'Paroxysmal Nocturnal Dyspnea (PND)',
                                  'question': 'Has the patient woken suddenly at night short of breath?',
                                  'type': 'boolean'},
 'peripheral_edema': {'category': 'Renal',
                      'id': 'peripheral_edema',
                      'name': 'Leg or Ankle Swelling',
                      'question': 'Is there new swelling of the legs, ankles, or feet?',
                      'type': 'boolean'},
 'peritonitis': {'category': 'Emergency gastrointestinal',
                 'id': 'peritonitis',
                 'name': 'Rigid or Very Tender Abdomen',
                 'question': 'Is the abdomen rigid or is pain severe with movement/touch?',
                 'type': 'boolean'},
 'persistent_chest_pressure': {'category': 'Emergency cardiovascular',
                               'id': 'persistent_chest_pressure',
                               'name': 'Persistent Chest Pressure',
                               'question': 'Is there persistent chest pressure or tightness?',
                               'type': 'boolean'},
 'persistent_vomiting': {'category': 'Emergency gastrointestinal',
                         'id': 'persistent_vomiting',
                         'name': 'Persistent Vomiting',
                         'question': 'Has vomiting persisted or occurred repeatedly in the last day?',
                         'type': 'boolean'},
 'petechiae': {'category': 'Dermatological',
               'id': 'petechiae',
               'name': 'Pinpoint Red or Purple Spots',
               'question': 'Are there new pinpoint red or purple spots that do not fade with pressure?',
               'type': 'boolean'},
 'photophobia': {'category': 'Neurological',
                 'id': 'photophobia',
                 'name': 'Light Sensitivity',
                 'question': 'Does bright light worsen symptoms or cause eye discomfort?',
                 'type': 'boolean'},
 'polyphagia': {'category': 'Metabolic',
                'id': 'polyphagia',
                'name': 'Increased Appetite (Polyphagia)',
                'question': "Has the patient's appetite increased markedly?",
                'type': 'boolean'},
 'polyuria_polydipsia': {'category': 'Metabolic',
                         'id': 'polyuria_polydipsia',
                         'name': 'Excessive Thirst & Frequent Urination',
                         'question': 'Is the patient drinking unusually large amounts of water and urinating '
                                     'constantly?',
                         'type': 'boolean'},
 'pulmonary_edema': {'category': 'Emergency respiratory',
                     'id': 'pulmonary_edema',
                     'name': 'Possible Fluid in Lungs',
                     'question': 'Is there severe breathlessness lying flat or pink frothy sputum?',
                     'type': 'boolean'},
 'purulent_sputum': {'category': 'Respiratory',
                     'id': 'purulent_sputum',
                     'name': 'Yellow/Green Phlegm',
                     'question': 'Is the patient coughing up yellow or green phlegm?',
                     'type': 'boolean'},
 'pus_discharge': {'category': 'Dermatological',
                   'id': 'pus_discharge',
                   'name': 'Pus or Purulent Discharge',
                   'question': 'Is there pus draining from a skin lesion or wound?',
                   'type': 'boolean'},
 'rapid_breathing': {'category': 'Emergency respiratory',
                     'id': 'rapid_breathing',
                     'name': 'Rapid Breathing',
                     'question': 'Is breathing unusually rapid?',
                     'type': 'boolean'},
 'recurrent_thrush': {'category': 'Metabolic',
                      'id': 'recurrent_thrush',
                      'name': 'Recurrent Thrush',
                      'question': 'Has the patient had recurrent thrush infections?',
                      'type': 'boolean'},
 'red_eye': {'category': 'Ophthalmic',
             'id': 'red_eye',
             'name': 'Red Eye / Conjunctival Injection',
             'question': 'Is one or both eyes red or injected?',
             'type': 'boolean'},
 'reduced_joint_movement': {'category': 'Musculoskeletal',
                            'id': 'reduced_joint_movement',
                            'name': 'Reduced Joint Movement',
                            'question': 'Is joint movement limited by pain or stiffness?',
                            'type': 'boolean'},
 'restlessness': {'category': 'Neurological',
                  'id': 'restlessness',
                  'name': 'Restlessness / Agitation',
                  'question': 'Is the patient restless, agitated, or unable to stay calm?',
                  'type': 'boolean'},
 'retro_orbital_pain': {'category': 'Neurological',
                        'id': 'retro_orbital_pain',
                        'name': 'Pain Behind the Eyes',
                        'question': 'Is there pain behind or around the eyes?',
                        'type': 'boolean'},
 'seizures': {'category': 'Emergency neurological',
              'id': 'seizures',
              'name': 'Seizures',
              'question': 'Has the patient had a seizure or convulsion?',
              'type': 'boolean'},
 'sensitivity_to_sound': {'category': 'Neurological',
                          'id': 'sensitivity_to_sound',
                          'name': 'Sound Sensitivity',
                          'question': 'Do normal sounds worsen the headache?',
                          'type': 'boolean'},
 'severe_abdominal_pain': {'category': 'Emergency gastrointestinal',
                           'id': 'severe_abdominal_pain',
                           'name': 'Severe Abdominal Pain',
                           'question': 'Is abdominal pain severe or rapidly worsening?',
                           'type': 'boolean'},
 'severe_dyspnea': {'category': 'Emergency respiratory',
                    'id': 'severe_dyspnea',
                    'name': 'Severe Breathlessness',
                    'question': 'Is there severe breathlessness at rest?',
                    'type': 'boolean'},
 'severe_respiratory_distress': {'category': 'Emergency respiratory',
                                 'id': 'severe_respiratory_distress',
                                 'name': 'Severe Respiratory Distress',
                                 'question': 'Is the patient struggling to breathe or unable to speak normally?',
                                 'type': 'boolean'},
 'shortness_of_breath': {'category': 'Respiratory',
                         'follow_ups': ['dyspnea_severity'],
                         'id': 'shortness_of_breath',
                         'name': 'Shortness of Breath / Dyspnea',
                         'question': 'Is the patient experiencing difficulty breathing or breathlessness?',
                         'type': 'boolean'},
 'silent_chest': {'category': 'Emergency respiratory',
                  'id': 'silent_chest',
                  'name': 'Very Quiet Chest During Asthma Attack',
                  'question': 'During severe wheeze, has breathing become very quiet with worsening distress?',
                  'type': 'boolean'},
 'skin_rash': {'category': 'Dermatological',
               'id': 'skin_rash',
               'name': 'Skin Rash / Lesions',
               'question': 'Is there any visible skin rash, hives, or lesions?',
               'type': 'boolean'},
 'slow_wound_healing': {'category': 'Metabolic',
                        'id': 'slow_wound_healing',
                        'name': 'Slow Wound Healing',
                        'question': 'Are cuts or wounds taking unusually long to heal?',
                        'type': 'boolean'},
 'slurred_speech': {'category': 'Neurological',
                    'id': 'slurred_speech',
                    'name': 'Slurred or Unclear Speech',
                    'question': "Is the patient's speech slurred or hard to understand?",
                    'type': 'boolean'},
 'sore_throat': {'category': 'Respiratory',
                 'id': 'sore_throat',
                 'name': 'Sore Throat',
                 'question': 'Does the patient have a sore or painful throat?',
                 'type': 'boolean'},
 'spontaneous_bleeding': {'category': 'Emergency',
                          'id': 'spontaneous_bleeding',
                          'name': 'Spontaneous Nose, Gum, or Skin Bleeding',
                          'question': 'Is there bleeding without an injury?',
                          'type': 'boolean'},
 'steatorrhea': {'category': 'Gastrointestinal',
                 'id': 'steatorrhea',
                 'name': 'Greasy or Fatty Stools (Steatorrhea)',
                 'question': 'Are stools unusually greasy, pale, or difficult to flush?',
                 'type': 'boolean'},
 'stridor_airway_swelling': {'category': 'Emergency allergy',
                             'id': 'stridor_airway_swelling',
                             'name': 'Noisy Breathing or Throat Swelling',
                             'question': 'Is there throat swelling or a high-pitched noise when breathing in?',
                             'type': 'boolean'},
 'sweating': {'category': 'Systemic',
              'id': 'sweating',
              'name': 'Sweating Episodes',
              'question': 'Has the patient had drenching sweating episodes, especially after fever?',
              'type': 'boolean'},
 'swollen_glands': {'category': 'Systemic',
                    'id': 'swollen_glands',
                    'name': 'Swollen Glands',
                    'question': 'Are any neck, armpit, or groin glands swollen?',
                    'type': 'boolean'},
 'syncope': {'category': 'Emergency',
             'id': 'syncope',
             'name': 'Fainting',
             'question': 'Has the patient fainted or collapsed?',
             'type': 'boolean'},
 'systolic_bp_above_180': {'category': 'Emergency cardiovascular',
                           'id': 'systolic_bp_above_180',
                           'name': 'Very High Blood Pressure',
                           'question': 'If measured, is the upper blood-pressure value above 180?',
                           'type': 'boolean'},
 'thirst': {'category': 'Fluid balance',
            'id': 'thirst',
            'name': 'Marked Thirst',
            'question': 'Is the patient unusually thirsty?',
            'type': 'boolean'},
 'thunderclap_onset': {'category': 'Emergency neurological',
                       'id': 'thunderclap_onset',
                       'name': 'Sudden Maximal Headache',
                       'question': 'Did the headache reach maximum intensity within seconds to minutes?',
                       'type': 'boolean'},
 'tinnitus': {'category': 'ENT',
              'id': 'tinnitus',
              'name': 'Tinnitus / Ringing in Ears',
              'question': 'Is the patient experiencing persistent ringing in the ears?',
              'type': 'boolean'},
 'tremor': {'category': 'Neurological',
            'id': 'tremor',
            'name': 'Tremor / Shaking',
            'question': 'Is there an involuntary shaking or tremor?',
            'type': 'boolean'},
 'unexplained_weight_loss': {'category': 'Constitutional',
                             'id': 'unexplained_weight_loss',
                             'name': 'Unexplained Weight Loss',
                             'question': 'Has the patient experienced significant unintentional weight loss recently?',
                             'type': 'boolean'},
 'uremic_encephalopathy': {'category': 'Emergency renal',
                           'id': 'uremic_encephalopathy',
                           'name': 'Confusion with Possible Kidney Failure',
                           'question': 'Is there new confusion or reduced alertness with very low urine output?',
                           'type': 'boolean'},
 'urinary_frequency': {'category': 'Urological',
                       'id': 'urinary_frequency',
                       'name': 'Frequent Urination',
                       'question': 'Is the patient urinating more often than usual?',
                       'type': 'boolean'},
 'urticaria_hives': {'category': 'Dermatological',
                     'id': 'urticaria_hives',
                     'name': 'Hives / Raised Itchy Welts',
                     'question': 'Are there raised, itchy welts that come and go?',
                     'type': 'boolean'},
 'vision_loss': {'category': 'Ophthalmic',
                 'id': 'vision_loss',
                 'name': 'Significant Vision Loss',
                 'question': 'Has there been a sudden or marked loss of vision?',
                 'type': 'boolean'},
 'visual_aura': {'category': 'Neurological',
                 'id': 'visual_aura',
                 'name': 'Visual Aura',
                 'question': 'Are there visual flashes, zig-zags, or blind spots before or during headache?',
                 'type': 'boolean'},
 'weakness': {'category': 'Systemic',
              'id': 'weakness',
              'name': 'Generalized Weakness',
              'question': 'Does the patient feel unusually weak?',
              'type': 'boolean'},
 'weight_gain': {'category': 'Constitutional',
                 'id': 'weight_gain',
                 'name': 'Unexplained Weight Gain',
                 'question': 'Has the patient gained weight unexpectedly or rapidly?',
                 'type': 'boolean'},
 'wheezing': {'category': 'Respiratory',
              'id': 'wheezing',
              'name': 'Wheezing',
              'question': 'Is there a whistling sound when breathing out?',
              'type': 'boolean'},
 'wound_drainage': {'category': 'Dermatological',
                    'id': 'wound_drainage',
                    'name': 'Wound Drainage',
                    'question': 'Is there fluid, pus, or drainage coming from a wound?',
                    'type': 'boolean'}}


aliases_dict = {'aching joints': 'joint_pain',
 'blood in urine': 'blood_in_urine',
 'bloody pee': 'blood_in_urine',
 'breathlessness': 'shortness_of_breath',
 'burning urination': 'dysuria',
 'cant breathe': 'shortness_of_breath',
 'cant control bladder': 'incontinence',
 'cant swallow': 'dysphagia',
 'chest pressure': 'chest_pain',
 'chest tightness': 'chest_pain',
 'chilly': 'chills',
 'cough blood': 'hemoptysis',
 'coughing blood': 'hemoptysis',
 'difficulty breathing': 'shortness_of_breath',
 'difficulty swallowing': 'dysphagia',
 'double vision': 'double_vision',
 'dyspnea': 'shortness_of_breath',
 'emesis': 'nausea_vomiting',
 'excessive thirst': 'polyuria_polydipsia',
 'feverish': 'fever',
 'frequent urination': 'polyuria_polydipsia',
 'heart pain': 'chest_pain',
 'high temp': 'fever',
 'hives': 'urticaria_hives',
 'hoarse voice': 'hoarseness',
 'hot body': 'fever',
 'icterus': 'jaundice',
 'joint pain': 'joint_pain',
 'loose bowel': 'diarrhea',
 'loose motion': 'diarrhea',
 'losing weight': 'unexplained_weight_loss',
 'neck pain': 'nuchal_rigidity',
 'night sweats': 'night_sweats',
 'painful pee': 'dysuria',
 'peeing a lot': 'polyuria_polydipsia',
 'pins and needles': 'paresthesia',
 'puking': 'nausea_vomiting',
 'pyrexia': 'fever',
 'shivering': 'chills',
 'short of breath': 'shortness_of_breath',
 'skin rash': 'skin_rash',
 'stiff neck': 'nuchal_rigidity',
 'sweating': 'sweating',
 'throwing up': 'nausea_vomiting',
 'tingling': 'paresthesia',
 'vomit': 'nausea_vomiting',
 'wake to pee': 'nocturia',
 'watery stool': 'diarrhea',
 'weight loss': 'unexplained_weight_loss',
 'welts': 'urticaria_hives',
 'yellow eyes': 'jaundice',
 'yellow skin': 'jaundice'}


def resolve_custom_symptoms(custom_text):
    text = (custom_text or "").lower()
    matches = [(phrase, symptom) for phrase, symptom in aliases_dict.items() if phrase in text]
    return {symptom for _, symptom in matches}, [
        {"custom_phrase": phrase, "canonical_id": symptom,
         "symptom_name": symptoms_dict.get(symptom, {}).get("name", symptom)}
        for phrase, symptom in matches]

def symptom_name(symptom):
    return symptoms_dict.get(symptom, {}).get("name", symptom.replace("_", " "))

def symptom_question(symptom):
    return symptoms_dict.get(symptom, {}).get("question", f"Is the patient experiencing {symptom.replace('_', ' ')}?")

